"""Cadastro das operacoes disponiveis para extracao do Score Card.

Todas usam a mesma automacao generica (automation/generic.py): login,
Reports > Reports, abrir o relatorio, aplicar filtros e exportar em
Excel. Para adicionar uma nova operacao, basta uma entrada aqui.

"sharepoint_folder" e o nome exato da subpasta (dentro da pasta do
SharePoint sincronizada via OneDrive) onde o relatorio dessa operacao e
salvo. Precisa bater com o nome da pasta que aparece no SharePoint.
"""

OPERATIONS = {
    "hugo_boss": {
        "label": "Hugo Boss",
        "login_url": "https://czcholspc003138.prg-dc.dhl.com:11217/rp/login",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Hugo Boss",
    },
    "hughes": {
        "label": "Hughes",
        "login_url": "https://czcholspc003008.prg-dc.dhl.com:11205/portal?siteId=CST#Menu-DEawt68KTrSaeNwjNA6mGg/reporting-ReportOpr////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Hughes",
    },
    "swa": {
        "label": "Swa",
        "login_url": "https://czcholspc003008.prg-dc.dhl.com:11205/portal?siteId=WH02#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "SWA",
    },
    "nike_fisia": {
        "label": "Nike/Fisia",
        "login_url": "https://czcholspc000211.prg-dc.dhl.com:11217/portal?siteId=LOU#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Nike",
    },
    "sumup": {
        "label": "Sumup",
        "login_url": "https://czcholspc002995.prg-dc.dhl.com:11205/portal?siteId=BR_0087&subsite=BR_5041_RED#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "SumUp",
    },
    "rede": {
        "label": "Rede",
        "login_url": "https://czcholspc002995.prg-dc.dhl.com:11205/portal?siteId=BR_5041_RED&subsite=BR_5041_RED#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Rede",
    },
    "jcb": {
        "label": "JCB",
        "login_url": "https://czcholspc002995.prg-dc.dhl.com:11205/portal?siteId=BR_5041_JCB&subsite=BR_5041_RED#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "JCB",
    },
    "lego": {
        "label": "Lego",
        "login_url": "https://czcholspc001643.prg-dc.dhl.com:11213/portal?siteId=BR_0087_1#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Lego",
    },
    "spacex": {
        "label": "SpaceX",
        "login_url": "https://czcholspc001643.prg-dc.dhl.com:11213/portal?siteId=BR_0087_8#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "SpaceX",
    },
    "hpe": {
        "label": "HPE",
        "login_url": "https://czcholspc001643.prg-dc.dhl.com:11213/portal?siteId=BR_0087_5#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "HPE",
    },
    "armani": {
        "label": "Armani",
        "login_url": "https://czcholspc001643.prg-dc.dhl.com:11213/portal?siteId=BR_5039#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "Armani",
    },
    "abb": {
        "label": "ABB",
        "login_url": "https://czcholspc001643.prg-dc.dhl.com:11213/portal?siteId=BR_0087_3#Menu-DEawt68KTrSaeNwjNA6mGg/mcs-Users////",
        "username_env": "DHL_USERNAME",
        "password_env": "DHL_PASSWORD",
        "report_name": "rptLMUserSummaryRaw",
        "date_range_type_text": "Las",
        "group_by_type_text": "User",
        "group_by_option": "User ID",
        "export_format": "EXCEL",
        "sharepoint_folder": "ABB",
    },
}
